### ISSUE TITLE
Make script for building executable for Windows

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/202020-Eyesafe-Project#1]
### 🚀Feature Request
Make script for building executable for Windows

### Description
Currently users need to install and setup python and all required dependencies to run the code

### Describe the solution you'd like
Make a batch file to run the `pyinstaller` commands to build the binaries
**DO NOT PUSH THE BUILD OUTPUT**
Also send the build output as zip attached as a comment in PR to make a release

### Additional context
The executable should run the service in background so users do not see an open terminal
References:
- https://realpython.com/pyinstaller-python/
- https://pyinstaller.org/en/stable/usage.html

**Comment by Jaggi037** [comment]
hey @PriyavKaneria can you please assign me this issue?

**Comment by PriyavKaneria** [comment]
According to rules @Jaggi037  has been assigned the issue on contrihub

**Comment by PriyavKaneria** [comment]
PR #6
