### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/202020-Eyesafe-Project#2]
### 🚀Feature Request
Add requirements.txt after setting up a working repo

**Comment by mangalgithub** [comment]
Can you assign this issue to me.

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by Aqua-16** [comment]
Can I please be assigned this task? I have the file ready.

**Comment by PriyavKaneria** [comment]
Due to multiple requests issue has been assigned based on fcfs on contrihub
