### ISSUE TITLE
Write python scripts that work on linux

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/202020-Eyesafe-Project#3]
### 🚀Feature Request
Write python script that works on linux to do the same task

### Description
Currently used libraries are dependent on windows internal binaries and system calls. So it only works on windows.

### Why is this feature important to you?
Many linux users would want to use the project but cannot right now

### Describe the solution you'd like
Write another python file `20-20-20-Eyesafe-project-linux.py` and write code that works on all UNIX distro

**Comment by MauryaRitesh** [comment]
@PriyavKaneria, Can you assign this issue to me?

**Comment by Aqua-16** [comment]
@PriyavKaneria I would like to work on this if possible. I have a solution ready.

**Comment by PriyavKaneria** [comment]
According to rules @lakshitrajput has been assigned the issue on contrihub

**Comment by Jaggi037** [comment]
hey @PriyavKaneria can you assign me this issue? i dont know why but the request of assignment is not going to you from contrihub page even though the alloted time of lakshit ( current assignee) is over.

**Comment by Aqua-16** [comment]
Yeah, I was also having the same issue in trying to request the reassignment of this problem.

**Comment by Nandika-A** [comment]
Hello @PriyavKaneria! Can I work on this issue?
