### ISSUE TITLE
isSet() deprecated warning

### ISSUE THREAD

**Issue by Aqua-16** [ContriHUB/202020-Eyesafe-Project#5]
Please choose your issue template from the following options:

# 1. 🐛Bug-Report
If something isn't working as expected 🤔

### Expected behavior

Run without warnings.

### Current behavior

Runs with the warning that isSet() is deprecated.

### Steps to reproduce

1. Clone the repository into a virtual environment.
2. Download dependencies.
3. Run the 20-20-20-Eyesafe-project.py file in terminal.

### Possible Solution
Convert the isSet() to is_set().

### Detailed Description (screenshots, code snippets etc.)
I noticed this while checking that the requirements.txt file was working correctly.
![image](https://github.com/ContriHUB/202020-Eyesafe-Project/assets/123102778/c1864a00-bbca-4d14-94d1-7c804b85565f)

**Comment by PriyavKaneria** [comment]
Issue has been added to contrihub

**Comment by eleensmathew** [comment]
Can I work on this? Im getting this error in the contrihub page - Assignment Request for [Issue #5](https://github.com/ContriHUB/202020-Eyesafe-Project/issues/5) of [202020-Eyesafe-Project](https://github.com/ContriHUB/202020-Eyesafe-Project) cannot 
be made by you currently.
